### ISSUE TITLE
「ログインをしてください」と表示される事象について。

### ISSUE THREAD

**Issue by bluafalko** [futoase/freee-gem#36]
はじめまして。
freee-gemを使おうと、MacのRuby2.3.0にインストールして、
Usageのコードをそのまま入れてみたのですが、

＞OAuth2::Error: : {"message"=>"ログインをして下さい"}
＞from /usr/local/lib/ruby/gems/2.3.0/gems/oauth2-1.1.0/lib/oauth2/client.rb:113:in `request'
＞from /usr/local/lib/ruby/gems/2.3.0/gems/oauth2-1.1.0/lib/oauth2/access_token.rb:107:in`request'
＞from /usr/local/lib/ruby/gems/2.3.0/gems/oauth2-1.1.0/lib/oauth2/access_token.rb:114:in `get'
＞from /usr/local/lib/ruby/gems/2.3.0/gems/freee-1.0.0/lib/freee/base.rb:69:in`get'
＞from /usr/local/lib/ruby/gems/2.3.0/gems/freee-1.0.0/lib/freee/user.rb:4:in `me'
と出てしまいます。これは何が原因か分かりますでしょうか。

どうぞよろしくお願い致します。

**Comment by futoase** [comment]
すみません、だいぶ間が空いてしまいました。後ほど確認しますm(_ _)m
